### ISSUE TITLE
Kodi install

### ISSUE THREAD

**Issue by donjuan21** [crazydevman/mute-profanity#28]
Hi Scott,

Congrats on the software. I tried uploading as an Add-on to Kodi but it failed to install. Any clues on how to get it setup? This is my first time installing an Add-on.

Thanks,

Don

**Comment by jtaylor113** [comment]
What version of kodi are you using and how did you attempt the install? You must download the zip version for the install. It can be a bit tricky, but is worth the trouble. I use this addon every day with kodi 16.

Jeff

**Comment by donjuan21** [comment]
I have version 16.0... When I downloaded from GitHub it came out as a regular folder. I then zipped it to install. I installed via the System -> Settings tabs. It was a bit confusing so I'm sure something didn't go right. I got a message in the lower right that said "Install Failed."

**Comment by donjuan21** [comment]
Thanks for responding Jeff. I've been at this all day. :-)

**Comment by jtaylor113** [comment]
There is a link on the main page that says "download zip". I think this is what I used to install on mine.

**Comment by donjuan21** [comment]
I got it. When I downloaded it on my MAC it came out as a folder. When I downloaded from my Dell it came out at a Zip. I'm good to go now. I'm watching my first movie now and it works pretty good. I think the actors did a lot of ad libbing because the subtitles don't have a lot of the cuss words. :-) It's getting most of them though... Thanks for your help.
