### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by jawhett1** [crazydevman/mute-profanity#33]
I love the idea of this but I need help with the setup. I downloaded the zip file and then Installed addon from the zip file. Then in the addon, I go to edit the movie, (I chose Deadpool because there are a lot of swear words) and then is says "mute profanity error: check the log for more details" I went to the event log and I dont see anything else. Any ideas?

**Comment by crazydevman** [comment]
From my understanding, the event log just tells you that you opened up the plugin, but doesn't actually contain the log statements from the plugin. Kodi actually has a real log file that would contain more info on your error. See more details here: http://kodi.wiki/view/Log_file/Advanced and here: http://kodi.wiki/view/Log_file/Easy
